name: Build

on:
  workflow_dispatch:

jobs:
  test-lint:
    name: Test and lint
    uses: ./.github/workflows/test-lint.yml
    secrets: inherit

  build:
    name: Build
    needs: test-lint
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: cargo build --release
      - if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: pngme
          path: target/release/pngme-rs
          if-no-files-found: error
          overwrite: true
